name: Deploy to Develop

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Mostrar diretório atual
        run: pwd

      - name: Listar arquivos
        run: ls -la

      - name: Mostrar variáveis de ambiente
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "HOME: $HOME"
