name: PHP CI with Coverage and PR

on:
  push:
    branches:
      - develop

jobs:
  unit-tests:
    name: Run Unit Tests with Coverage
    runs-on: ubuntu-latest
    outputs:
      coverage-ok: ${{ steps.check-coverage.outputs.coverage-ok }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker
        run: docker compose -f docker-compose.yml up -d --build

      - name: Listar arquivos do diretório dentro do container
        run: docker exec play-api ls -lah /var/www/
        
      - name: Run PHPUnit with coverage
        run: |
          docker exec play-api vendor/bin/phpunit \
            --coverage-clover /var/www/code/coverage.xml \
            /var/www/code/tests

      - name: Copy coverage file from container
        run: docker cp play-api:/var/www/code/coverage.xml ./coverage.xml

      - name: Check coverage percentage
        id: check-coverage
        run: |
          COVERAGE=$(grep -oPm1 '(?<=<metrics .*line-rate=")[^"]+' coverage.xml)
          PERCENT=$(echo "$COVERAGE * 100" | bc -l | awk '{printf "%.2f", $0}')
          echo "Cobertura: $PERCENT%"
          if (( $(echo "$PERCENT >= 70" | bc -l) )); then
            echo "✅ Cobertura OK"
            echo "coverage-ok=true" >> $GITHUB_OUTPUT
          else
            echo "❌ Cobertura insuficiente"
            echo "coverage-ok=false" >> $GITHUB_OUTPUT
          fi



