name: PHP CI with Coverage and PR

on:
  push:
    branches:
      - develop

jobs:
  unit-tests:
    name: Run Unit Tests with Coverage
    runs-on: ubuntu-latest
    outputs:
      coverage-ok: ${{ steps.check-coverage.outputs.coverage-ok }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Diretorio APP
        run: echo "Working directory is ${{ github.workspace }}"

      - name: SETANDO PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: xdebug 

      - name: Copy .env
        run: php -r "file_exists('${{ github.workspace }}/code/.env') || copy('${{ github.workspace }}/code/.env.example', '${{ github.workspace }}/code/.env');"
    
      - name: Install Dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
        working-directory: ${{ github.workspace }}/code
        
      - name: Generate key
        run: php artisan key:generate
        working-directory: ${{ github.workspace }}/code
          
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
        working-directory: ${{ github.workspace }}/code

      - name: Run PHPUnit with coverage
        run: |
          vendor/bin/phpunit \
            --coverage-clover coverage.xml \
            tests
        working-directory: ${{ github.workspace }}/code
    
      - name: Listar diretório após cobertura
        run: ls -la
        working-directory: ${{ github.workspace }}/code



