name: PHP CI with Coverage and PR

on:
  push:
    branches:
      - develop

jobs:
  unit-tests:
    name: Run Unit Tests with Coverage
    runs-on: ubuntu-latest
    outputs:
      coverage-ok: ${{ steps.check-coverage.outputs.coverage-ok }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        run: docker compose -f docker-compose.yml up -d --build

      - name: Run PHPUnit with coverage
        run: |
          docker exec play-api ./vendor/bin/phpunit \
            --coverage-clover /var/www/code/coverage.xml \
            /var/www/code/tests

      - name: Copy coverage file from container
        run: docker cp play-api:/var/www/code/coverage.xml ./coverage.xml

      - name: Check coverage percentage
        id: check-coverage
        run: |
          COVERAGE=$(grep -oPm1 '(?<=<metrics .*line-rate=")[^"]+' coverage.xml)
          PERCENT=$(echo "$COVERAGE * 100" | bc -l | awk '{printf "%.2f", $0}')
          echo "Cobertura: $PERCENT%"
          if (( $(echo "$PERCENT >= 70" | bc -l) )); then
            echo "✅ Cobertura OK"
            echo "coverage-ok=true" >> $GITHUB_OUTPUT
          else
            echo "❌ Cobertura insuficiente"
            echo "coverage-ok=false" >> $GITHUB_OUTPUT
          fi

  code-analysis:
    name: Run SonarCloud Analysis
    needs: unit-tests
    if: needs.unit-tests.outputs.coverage-ok == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run SonarCloud scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: ./code
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
          SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}

  create-pull-request:
    name: Create Pull Request Automatically
    needs: [unit-tests, code-analysis]
    if: needs.unit-tests.outputs.coverage-ok == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create new branch
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git checkout -b feature/auto-pr

      - name: Dummy commit (opcional)
        run: |
          echo "// trigger pr" >> .github/trigger.php
          git add .github/trigger.php
          git commit -m "chore: trigger auto PR"

      - name: Push branch
        run: git push origin feature/auto-pr

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          head: feature/auto-pr
          title: "PR automático: cobertura OK e análise feita"
          body: |
            ✅ Testes unitários com cobertura ≥ 70%
            ✅ SonarCloud executado com sucesso
