name: PHP CI with Coverage and PR

on:
  push:
    branches:
      - develop

jobs:
  unit-tests:
    name: Run Unit Tests with Coverage
    runs-on: ubuntu-latest
    outputs:
      coverage-ok: ${{ steps.check-coverage.outputs.coverage-ok }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Diretorio APP
        run: echo "Working directory is ${{ github.workspace }}"

      - name: SETANDO PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: xdebug 

      - name: Copy .env
        run: php -r "file_exists('${{ github.workspace }}/code/.env') || copy('${{ github.workspace }}/code/.env.example', '${{ github.workspace }}/code/.env');"
    
      - name: Install Dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
        working-directory: ${{ github.workspace }}/code
        
      - name: Generate key
        run: php artisan key:generate
        working-directory: ${{ github.workspace }}/code
          
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
        working-directory: ${{ github.workspace }}/code

      - name: Run PHPUnit with coverage
        run: |
          vendor/bin/phpunit \
            --coverage-clover coverage.xml \
            tests
        working-directory: ${{ github.workspace }}/code

      - name: Verificar cobertura mínima
        id: check-coverage
        run: |
          total=$(awk -F'"' '/<metrics .*statements="/ { print $18 }' coverage.xml | tail -1)
          covered=$(awk -F'"' '/<metrics .*coveredstatements="/ { print $24 }' coverage.xml | tail -1)

          echo "Total de statements: $total"
          echo "Statements cobertos: $covered"

          coverage_percent=$(awk "BEGIN {printf \"%.2f\", ($covered / $total) * 100}")
          echo "Cobertura: $coverage_percent%"

          echo "coverage_percent=$coverage_percent" >> $GITHUB_OUTPUT

          if (( $(echo "$coverage_percent >= 70.0" | bc -l) )); then
            echo "coverage-ok=true" >> $GITHUB_OUTPUT
          else
            echo "coverage-ok=false" >> $GITHUB_OUTPUT
          fi
        working-directory: ${{ github.workspace }}/code
  
  SonarCloudScan:
    needs: unit-tests
    if: needs.unit-tests.outputs.coverage-ok == 'true'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código da branch atual
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # necessário para o Sonar comparar branches

    - name: Setup PHP (ou outro setup necessário)
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2' # ou a versão que seu projeto usa

    - name: Instalar dependências
      run: composer install --no-interaction --prefer-dist

    - name: Install Dependencies
      run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      working-directory: ${{ github.workspace }}/code

    - name: Rodar SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v2
      with:
        args: >
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
          -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          -Dsonar.php.coverage.reportPaths=coverage.xml
          -Dsonar.pullrequest.branch=${{ github.head_ref }}
          -Dsonar.pullrequest.base=${{ github.base_ref }}


  create-pr:
    needs: unit-tests
    if: needs.unit-tests.outputs.coverage-ok == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Obter nome da branch de origem
        id: vars
        run: echo "branch_name=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - name: Criar Pull Request para develop
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "Cobertura de testes ≥ 70% - PR automático"
          branch: auto/coverage-pass
          base: develop
          title: "Cobertura OK: PR automático para develop"
          body: |
            A cobertura de testes atingiu **${{ needs.unit-tests.outputs.coverage_percent }}%**, superando o mínimo de 70%.
            Este PR foi criado automaticamente para promover as mudanças da branch `${{ steps.vars.outputs.branch_name }}` para `develop`.

          



